export type GradeBand = 'preK' | 'k1' | 'g2' | '35' | '68'

export interface InteractiveWorksheetDoc {
  id: string
  title: string
  description: string
  grades: GradeBand[]
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced'
  focus: string[]
}

export interface InteractiveCategory {
  id: string
  label: string
  icon: string
  tagline: string
  longDescription: string
  topics: string[]
  docs: InteractiveWorksheetDoc[]
}

export const INTERACTIVE_GRADE_OPTIONS: Array<{ id: GradeBand; label: string }> = [
  { id: 'preK', label: 'Preschool' },
  { id: 'k1', label: 'K–1' },
  { id: 'g2', label: '2nd–3rd' },
  { id: '35', label: '4th–5th' },
  { id: '68', label: '6th–8th' },
]

const makeDoc = (
  doc: Partial<InteractiveWorksheetDoc> & { id: string; title: string }
): InteractiveWorksheetDoc => ({
  description: '',
  grades: ['k1'],
  difficulty: 'Beginner',
  focus: [],
  ...doc,
})

export const INTERACTIVE_CATEGORIES: InteractiveCategory[] = [
  {
    id: 'math',
    label: 'Math',
    icon: '🧠',
    tagline: 'Daily math practice with puzzles, drills, and logic.',
    longDescription:
      'Auto-generate interactive math worksheets that mix fluency drills with puzzles, word problems, and visual models. Perfect for warm-ups, stations, or homework.',
    topics: [
      'Addition & subtraction',
      'Fractions and place value',
      'Word problems',
      'Logic grids and puzzles',
    ],
    docs: [
      makeDoc({
        id: 'interactive-math-rhythm',
        title: 'Number Pattern Rhythm',
        description: 'Complete number patterns with skip counting sequences. Each sheet generates unique patterns.',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Intermediate',
        focus: ['patterns', 'skip counting', 'number sense'],
      }),
      makeDoc({
        id: 'interactive-math-race',
        title: 'Math Race Challenge',
        description: 'Timed addition and subtraction challenges with varying difficulty levels.',
        grades: ['preK', 'k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['speed', 'fact fluency', 'mental math'],
      }),
      makeDoc({
        id: 'interactive-math-puzzle',
        title: 'Equation Puzzle Box',
        description: 'Solve missing number equations arranged in puzzle format. Each puzzle is unique.',
        grades: ['preK', 'k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['algebraic thinking', 'problem solving'],
      }),
      makeDoc({
        id: 'interactive-math-shapes',
        title: 'Geometry Shape Challenge',
        description: 'Identify, count, and classify shapes with interactive exercises.',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Intermediate',
        focus: ['geometry', 'classification', 'spatial reasoning'],
      }),
      makeDoc({
        id: 'interactive-math-money',
        title: 'Money Math Mastery',
        description: 'Count coins, make change, and solve money word problems.',
        grades: ['g2', '35'],
        difficulty: 'Intermediate',
        focus: ['money', 'decimals', 'real-world math'],
      }),
      makeDoc({
        id: 'interactive-math-fractions',
        title: 'Fraction Fun Practice',
        description: 'Compare fractions, find equivalents, and solve fraction operations.',
        grades: ['35', '68'],
        difficulty: 'Advanced',
        focus: ['fractions', 'equivalency', 'operations'],
      }),
      makeDoc({
        id: 'interactive-math-measurement',
        title: 'Measurement Mission',
        description: 'Practice length, weight, volume, and time measurement conversions.',
        grades: ['g2', '35'],
        difficulty: 'Intermediate',
        focus: ['measurement', 'units', 'conversion'],
      }),
      makeDoc({
        id: 'interactive-math-algebra',
        title: 'Algebra Basics Practice',
        description: 'Solve equations, work with variables, and practice algebraic expressions.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['algebra', 'equations', 'variables', 'expressions'],
      }),
      makeDoc({
        id: 'interactive-math-percentages',
        title: 'Percentage & Ratio Mastery',
        description: 'Calculate percentages, work with ratios, and solve proportion problems.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['percentages', 'ratios', 'proportions', 'real-world math'],
      }),
      makeDoc({
        id: 'interactive-math-geometry',
        title: 'Advanced Geometry Challenge',
        description: 'Calculate area, perimeter, volume, and work with angles and transformations.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['geometry', 'area', 'perimeter', 'volume', 'angles'],
      }),
      makeDoc({
        id: 'interactive-math-statistics',
        title: 'Data & Statistics Explorer',
        description: 'Analyze data sets, create graphs, calculate mean, median, mode, and interpret statistics.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['statistics', 'data analysis', 'graphs', 'mean median mode'],
      }),
      makeDoc({
        id: 'interactive-math-word-problems',
        title: 'Multi-Step Word Problems',
        description: 'Solve complex word problems requiring multiple steps and critical thinking.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['word problems', 'problem solving', 'multi-step', 'critical thinking'],
      }),
      makeDoc({
        id: 'interactive-math-counting',
        title: 'Counting & Number Recognition',
        description: 'Practice counting objects, recognizing numbers, and matching quantities to numerals.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['counting', 'number recognition', 'one-to-one correspondence'],
      }),
      makeDoc({
        id: 'interactive-math-tens-frames',
        title: 'Tens Frames Practice',
        description: 'Use tens frames to understand numbers, addition, and subtraction visually.',
        grades: ['preK', 'k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['number sense', 'addition', 'subtraction', 'visual math'],
      }),
      makeDoc({
        id: 'interactive-math-multiplication',
        title: 'Multiplication Mastery',
        description: 'Practice multiplication facts, arrays, and multiplication word problems.',
        grades: ['g2', '35'],
        difficulty: 'Intermediate',
        focus: ['multiplication', 'arrays', 'fact fluency', 'word problems'],
      }),
      makeDoc({
        id: 'interactive-math-division',
        title: 'Division Practice',
        description: 'Learn division facts, use arrays, and solve division word problems.',
        grades: ['g2', '35'],
        difficulty: 'Intermediate',
        focus: ['division', 'fact families', 'word problems', 'remainders'],
      }),
      makeDoc({
        id: 'interactive-math-place-value',
        title: 'Place Value Explorer',
        description: 'Understand ones, tens, hundreds, and thousands place with interactive exercises.',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Intermediate',
        focus: ['place value', 'number sense', 'expanded form', 'comparing numbers'],
      }),
      makeDoc({
        id: 'interactive-math-time',
        title: 'Time & Clock Practice',
        description: 'Read analog and digital clocks, calculate elapsed time, and solve time word problems.',
        grades: ['g2', '35'],
        difficulty: 'Intermediate',
        focus: ['time', 'clocks', 'elapsed time', 'word problems'],
      }),
      makeDoc({
        id: 'interactive-math-graphing',
        title: 'Data & Graphing Practice',
        description: 'Create bar graphs, pictographs, and line plots from data sets.',
        grades: ['g2', '35'],
        difficulty: 'Intermediate',
        focus: ['graphing', 'data', 'bar graphs', 'pictographs'],
      }),
      makeDoc({
        id: 'interactive-math-rounding',
        title: 'Rounding Numbers',
        description: 'Round numbers to the nearest ten, hundred, and thousand.',
        grades: ['35', '68'],
        difficulty: 'Intermediate',
        focus: ['rounding', 'estimation', 'number sense'],
      }),
      makeDoc({
        id: 'interactive-math-decimals',
        title: 'Decimal Operations',
        description: 'Add, subtract, multiply, and divide decimals with real-world applications.',
        grades: ['35', '68'],
        difficulty: 'Advanced',
        focus: ['decimals', 'operations', 'place value', 'real-world math'],
      }),
      makeDoc({
        id: 'interactive-math-integers',
        title: 'Integers & Number Line',
        description: 'Work with positive and negative numbers, absolute value, and coordinate plane.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['integers', 'number line', 'absolute value', 'coordinate plane'],
      }),
      makeDoc({
        id: 'interactive-math-exponents',
        title: 'Exponents & Powers',
        description: 'Understand exponents, powers, and scientific notation.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['exponents', 'powers', 'scientific notation', 'order of operations'],
      }),
    ],
  },
  {
    id: 'reading',
    label: 'Reading',
    icon: '📚',
    tagline: 'Short passages with comprehension checks.',
    longDescription:
      'Print fiction and nonfiction passages with leveled questions, vocabulary focus, and answer keys. Includes grade-specific inference and context clues practice.',
    topics: [
      'Fiction & nonfiction passages',
      'Inference questions',
      'Vocabulary in context',
      'Reading logs & prompts',
    ],
    docs: [
      makeDoc({
        id: 'interactive-reading-adventure',
        title: 'Reading Adventure Quest',
        description: 'Interactive story passages with multiple choice and short answer questions. Each sheet features a new story.',
        grades: ['k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['comprehension', 'inference', 'vocabulary'],
      }),
      makeDoc({
        id: 'interactive-reading-prek',
        title: 'Picture Story Time',
        description: 'Simple picture-based stories with yes/no questions and basic comprehension activities.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['picture reading', 'basic comprehension', 'storytelling'],
      }),
      makeDoc({
        id: 'interactive-reading-alphabet',
        title: 'Alphabet & Letter Recognition',
        description: 'Practice recognizing letters, matching uppercase and lowercase, and beginning sounds.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['letter recognition', 'alphabet', 'phonics'],
      }),
      makeDoc({
        id: 'interactive-reading-sightwords',
        title: 'Sight Word Practice',
        description: 'Practice reading and writing common sight words with fun activities.',
        grades: ['preK', 'k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['sight words', 'word recognition', 'reading fluency'],
      }),
      makeDoc({
        id: 'interactive-reading-detective',
        title: 'Reading Detective Challenge',
        description: 'Find clues in the text to answer mystery questions. New mysteries each time.',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Intermediate',
        focus: ['text evidence', 'critical thinking', 'inference'],
      }),
      makeDoc({
        id: 'interactive-reading-storymap',
        title: 'Story Map Builders',
        description: 'Retell fiction stories with beginning, middle, and ending organizers plus clue gathering practice.',
        grades: ['k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['story structure', 'retelling', 'comprehension'],
      }),
      makeDoc({
        id: 'interactive-reading-vocab',
        title: 'Vocabulary Builder Workshop',
        description: 'Context clues exercises with word matching and sentence completion.',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['vocabulary', 'context clues', 'word meaning'],
      }),
      makeDoc({
        id: 'interactive-reading-summary',
        title: 'Summary & Main Idea',
        description: 'Practice identifying main ideas and writing concise summaries.',
        grades: ['g2', '35'],
        difficulty: 'Intermediate',
        focus: ['main idea', 'summarizing', 'key details'],
      }),
      makeDoc({
        id: 'interactive-reading-compare',
        title: 'Compare & Contrast Passages',
        description: 'Read multiple texts and compare themes, characters, or information.',
        grades: ['35', '68'],
        difficulty: 'Advanced',
        focus: ['comparing', 'analysis', 'critical thinking'],
      }),
      makeDoc({
        id: 'interactive-reading-literary-analysis',
        title: 'Literary Analysis Workshop',
        description: 'Analyze literary elements, themes, symbolism, and author\'s purpose in fiction texts.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['literary analysis', 'themes', 'symbolism', 'author\'s purpose'],
      }),
      makeDoc({
        id: 'interactive-reading-research',
        title: 'Research & Evidence Builder',
        description: 'Practice finding and evaluating sources, citing evidence, and building arguments from multiple texts.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['research', 'evidence', 'citations', 'argument building'],
      }),
      makeDoc({
        id: 'interactive-reading-fluency',
        title: 'Reading Fluency Practice',
        description: 'Practice reading with expression, accuracy, and appropriate pacing. Includes repeated reading exercises.',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Intermediate',
        focus: ['reading fluency', 'expression', 'accuracy'],
      }),
      makeDoc({
        id: 'interactive-reading-character',
        title: 'Character Analysis Workshop',
        description: 'Analyze character traits, motivations, and development in stories.',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['character analysis', 'literary elements', 'comprehension'],
      }),
    ],
  },
  {
    id: 'writing',
    label: 'Writing',
    icon: '✍️',
    tagline: 'Creative prompts and handwriting practice.',
    longDescription:
      'Spark writing with printable prompts, handwriting practice, and planners that guide students from sentences to paragraphs.',
    topics: [
      'Sentence structure',
      'Creative prompts',
      'Handwriting practice',
      'Goal-setting journals',
    ],
    docs: [
      makeDoc({
        id: 'interactive-writing-prompts',
        title: 'Creative Writing Prompts',
        description: 'Unique story starters and creative writing prompts that change with each generation.',
        grades: ['g2', '35'],
        difficulty: 'Beginner',
        focus: ['creativity', 'storytelling', 'imagination'],
      }),
      makeDoc({
        id: 'interactive-writing-prek',
        title: 'Drawing & Labeling',
        description: 'Draw pictures and label them with simple words. Perfect for early writers.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['drawing', 'labeling', 'early writing'],
      }),
      makeDoc({
        id: 'interactive-writing-trace',
        title: 'Letter & Word Tracing',
        description: 'Trace letters and simple words to build handwriting skills and letter recognition.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['handwriting', 'letter formation', 'fine motor'],
      }),
      makeDoc({
        id: 'interactive-writing-pictures',
        title: 'Picture Story Starters',
        description: 'Look at pictures and write simple sentences or stories about what you see.',
        grades: ['preK', 'k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['storytelling', 'imagination', 'descriptive writing'],
      }),
      makeDoc({
        id: 'interactive-writing-sentences',
        title: 'Sentence Builder Workshop',
        description: 'Practice building complete sentences with varied structures and punctuation.',
        grades: ['k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['sentence structure', 'grammar', 'punctuation'],
      }),
      makeDoc({
        id: 'interactive-writing-narrative',
        title: 'Narrative Writing Practice',
        description: 'Write short stories with beginning, middle, and end. Includes story planning templates.',
        grades: ['g2', '35'],
        difficulty: 'Intermediate',
        focus: ['narrative writing', 'story structure', 'creative writing'],
      }),
      makeDoc({
        id: 'interactive-writing-poetry',
        title: 'Poetry Writing Practice',
        description: 'Guided poetry exercises with rhyming, haiku, and free verse prompts.',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['poetry', 'figurative language', 'self-expression'],
      }),
      makeDoc({
        id: 'interactive-writing-opinion',
        title: 'Opinion Writing Framework',
        description: 'Structured templates for opinion writing with prompts and evidence gathering.',
        grades: ['35', '68'],
        difficulty: 'Advanced',
        focus: ['opinion writing', 'persuasion', 'evidence'],
      }),
      makeDoc({
        id: 'interactive-writing-informative',
        title: 'Informative Writing Guide',
        description: 'Learn to write informative paragraphs and essays with facts, details, and explanations.',
        grades: ['35', '68'],
        difficulty: 'Advanced',
        focus: ['informative writing', 'expository writing', 'facts and details'],
      }),
      makeDoc({
        id: 'interactive-writing-research',
        title: 'Research Paper Planner',
        description: 'Organize research, create outlines, and structure research papers with proper citations.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['research', 'outlining', 'citations', 'academic writing'],
      }),
      makeDoc({
        id: 'interactive-writing-essay',
        title: 'Essay Writing Workshop',
        description: 'Practice writing structured essays with thesis statements, body paragraphs, and conclusions.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['essay writing', 'thesis statements', 'structure', 'academic writing'],
      }),
      makeDoc({
        id: 'interactive-writing-argumentative',
        title: 'Argumentative Writing Practice',
        description: 'Develop arguments with claims, evidence, and reasoning. Practice persuasive writing skills.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['argumentative writing', 'claims', 'evidence', 'reasoning'],
      }),
    ],
  },
  {
    id: 'science',
    label: 'Science',
    icon: '🌎',
    tagline: 'Hands-on STEM prompts and lab reflections.',
    longDescription:
      'Bring STEM topics to life with printable lab guides, observation charts, and quick facts that connect to real-world concepts.',
    topics: ['Human body', 'Plants & animals', 'Earth science', 'Space & physics'],
    docs: [
      makeDoc({
        id: 'interactive-science-observation',
        title: 'Science Observation Journal',
        description: 'Daily observation logs for experiments and nature studies. Each sheet features new prompts.',
        grades: ['g2', '35'],
        difficulty: 'Intermediate',
        focus: ['observation', 'scientific method', 'recording'],
      }),
      makeDoc({
        id: 'interactive-science-prek',
        title: 'Nature Explorer',
        description: 'Simple nature observation activities with pictures and basic questions about plants, animals, and weather.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['nature observation', 'basic science', 'curiosity'],
      }),
      makeDoc({
        id: 'interactive-science-senses',
        title: 'Five Senses Explorer',
        description: 'Explore the five senses through hands-on activities and observation exercises.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['five senses', 'observation', 'scientific method'],
      }),
      makeDoc({
        id: 'interactive-science-plants',
        title: 'Plant Explorer',
        description: 'Learn about plants, their parts, and how they grow through simple activities.',
        grades: ['preK', 'k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['plants', 'plant parts', 'life cycles'],
      }),
      makeDoc({
        id: 'interactive-science-animals',
        title: 'Animal Classification',
        description: 'Learn about different types of animals, their habitats, and characteristics.',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Beginner',
        focus: ['animals', 'classification', 'habitats'],
      }),
      makeDoc({
        id: 'interactive-science-space',
        title: 'Space & Astronomy Explorer',
        description: 'Learn about planets, stars, and space phenomena with interactive activities.',
        grades: ['35', '68'],
        difficulty: 'Intermediate',
        focus: ['astronomy', 'space science', 'planets'],
      }),
      makeDoc({
        id: 'interactive-science-lifecycle',
        title: 'Life Cycle Explorer',
        description: 'Interactive worksheets exploring plant and animal life cycles.',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Beginner',
        focus: ['life cycles', 'biology', 'sequencing'],
      }),
      makeDoc({
        id: 'interactive-science-states',
        title: 'States of Matter Lab',
        description: 'Hands-on activities exploring solid, liquid, gas with observation charts.',
        grades: ['g2', '35'],
        difficulty: 'Intermediate',
        focus: ['matter', 'physical science', 'experimentation'],
      }),
      makeDoc({
        id: 'interactive-science-weather',
        title: 'Weather Watcher Journal',
        description: 'Track weather patterns, temperature, and observations over time.',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Beginner',
        focus: ['weather', 'data collection', 'patterns'],
      }),
      makeDoc({
        id: 'interactive-science-chemistry',
        title: 'Chemistry Basics Lab',
        description: 'Explore atoms, molecules, chemical reactions, and the periodic table.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['chemistry', 'atoms', 'molecules', 'periodic table'],
      }),
      makeDoc({
        id: 'interactive-science-physics',
        title: 'Physics Fundamentals',
        description: 'Learn about forces, motion, energy, and simple machines with hands-on activities.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['physics', 'forces', 'motion', 'energy'],
      }),
      makeDoc({
        id: 'interactive-science-ecology',
        title: 'Ecology & Environment Study',
        description: 'Explore ecosystems, food webs, environmental issues, and conservation.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['ecology', 'ecosystems', 'environment', 'conservation'],
      }),
    ],
  },
  {
    id: 'geography',
    label: 'Social Studies',
    icon: '🗺️',
    tagline: 'Maps, timelines, and culture snapshots.',
    longDescription:
      'Download printable social studies worksheets that cover maps, history milestones, communities, and civics discussions.',
    topics: ['Continents & oceans', 'Timelines', 'Communities', 'Civics'],
    docs: [
      makeDoc({
        id: 'interactive-geography-map',
        title: 'Interactive Map Skills',
        description: 'Practice reading maps, using legends, and identifying locations. Each sheet features different maps.',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Beginner',
        focus: ['map skills', 'spatial awareness', 'geography'],
      }),
      makeDoc({
        id: 'interactive-geography-prek',
        title: 'My Community Explorer',
        description: 'Learn about places in the community, home, and school with simple maps and pictures.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['community', 'places', 'spatial concepts'],
      }),
      makeDoc({
        id: 'interactive-geography-places',
        title: 'Places & Landmarks',
        description: 'Learn about important places, landmarks, and locations in your community and country.',
        grades: ['preK', 'k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['places', 'landmarks', 'geography'],
      }),
      makeDoc({
        id: 'interactive-geography-seasons',
        title: 'Seasons & Weather Around the World',
        description: 'Learn about different seasons, weather patterns, and how they vary in different places.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['seasons', 'weather', 'geography'],
      }),
      makeDoc({
        id: 'interactive-geography-continents',
        title: 'Continents & Oceans Explorer',
        description: 'Learn about the seven continents and five oceans with maps and activities.',
        grades: ['g2', '35'],
        difficulty: 'Intermediate',
        focus: ['continents', 'oceans', 'world geography'],
      }),
      makeDoc({
        id: 'interactive-geography-culture',
        title: 'Culture Explorer',
        description: 'Learn about different cultures, traditions, and communities around the world.',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['culture', 'world studies', 'diversity'],
      }),
      makeDoc({
        id: 'interactive-geography-history',
        title: 'Historical Timeline Builder',
        description: 'Create timelines and learn about historical events and figures.',
        grades: ['35', '68'],
        difficulty: 'Intermediate',
        focus: ['history', 'timelines', 'chronology'],
      }),
      makeDoc({
        id: 'interactive-geography-government',
        title: 'Civics & Government Explorer',
        description: 'Learn about government structure, citizenship, rights, and responsibilities.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['government', 'civics', 'citizenship', 'rights'],
      }),
      makeDoc({
        id: 'interactive-geography-economics',
        title: 'Economics Basics',
        description: 'Explore supply and demand, budgeting, financial literacy, and economic systems.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['economics', 'supply and demand', 'budgeting', 'financial literacy'],
      }),
    ],
  },
  {
    id: 'grammar',
    label: 'Grammar & Vocabulary',
    icon: '💬',
    tagline: 'Parts of speech, verb tenses, and word play.',
    longDescription:
      'Print grammar drills, vocabulary quizzes, and sentence repair challenges that work for both native speakers and ESL learners.',
    topics: ['Parts of speech', 'Verb tense practice', 'Synonyms & antonyms', 'Sentence correction'],
    docs: [
      makeDoc({
        id: 'interactive-grammar-parts',
        title: 'Parts of Speech Practice',
        description: 'Identify nouns, verbs, adjectives, and adverbs in sentences. Each sheet has new sentences.',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Beginner',
        focus: ['parts of speech', 'grammar', 'sentence analysis'],
      }),
      makeDoc({
        id: 'interactive-grammar-prek',
        title: 'Word & Picture Match',
        description: 'Match simple words with pictures and identify basic word types.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['word recognition', 'vocabulary', 'matching'],
      }),
      makeDoc({
        id: 'interactive-grammar-rhyming',
        title: 'Rhyming Words Practice',
        description: 'Identify and match rhyming words through fun activities.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['rhyming', 'phonemic awareness', 'word families'],
      }),
      makeDoc({
        id: 'interactive-grammar-capitalization',
        title: 'Capitalization & Punctuation',
        description: 'Practice proper capitalization and punctuation in sentences.',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Beginner',
        focus: ['capitalization', 'punctuation', 'sentence structure'],
      }),
      makeDoc({
        id: 'interactive-grammar-plurals',
        title: 'Plurals & Possessives',
        description: 'Learn to form plurals and possessives correctly.',
        grades: ['g2', '35'],
        difficulty: 'Intermediate',
        focus: ['plurals', 'possessives', 'grammar rules'],
      }),
      makeDoc({
        id: 'interactive-grammar-tenses',
        title: 'Verb Tense Mastery',
        description: 'Practice past, present, and future tense with verb conjugation exercises.',
        grades: ['g2', '35'],
        difficulty: 'Intermediate',
        focus: ['verb tenses', 'grammar', 'conjugation'],
      }),
      makeDoc({
        id: 'interactive-grammar-antonyms',
        title: 'Synonyms & Antonyms Challenge',
        description: 'Match words with synonyms and antonyms to expand vocabulary.',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['vocabulary', 'word relationships', 'language'],
      }),
      makeDoc({
        id: 'interactive-grammar-advanced',
        title: 'Advanced Grammar Practice',
        description: 'Practice complex sentence structures, clauses, phrases, and advanced punctuation.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['grammar', 'sentence structure', 'clauses', 'punctuation'],
      }),
      makeDoc({
        id: 'interactive-grammar-vocab',
        title: 'Academic Vocabulary Builder',
        description: 'Learn and practice academic vocabulary words with context clues and usage exercises.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['vocabulary', 'academic language', 'context clues'],
      }),
    ],
  },
  {
    id: 'art',
    label: 'Art & Coloring',
    icon: '🎨',
    tagline: 'Creative prompts and color-by-number fun.',
    longDescription:
      'Keep creativity alive with coloring adventures, symmetry drawing, and design challenges that double as calming brain breaks.',
    topics: ['Color-by-number', 'Seasonal themes', 'Pattern & symmetry', 'Drawing prompts'],
    docs: [
      makeDoc({
        id: 'interactive-art-design',
        title: 'Creative Design Challenge',
        description: 'Fun coloring pages with simple pictures to color. Perfect for young artists!',
        grades: ['preK', 'k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['coloring', 'fine motor', 'creativity'],
      }),
      makeDoc({
        id: 'interactive-art-shapes',
        title: 'Shape Art & Drawing',
        description: 'Create art using basic shapes. Draw and color shapes to make pictures.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['shapes', 'drawing', 'creativity'],
      }),
      makeDoc({
        id: 'interactive-art-colorwheel',
        title: 'Color Theory Practice',
        description: 'Color pictures with the correct colors. Learn colors while having fun!',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Beginner',
        focus: ['colors', 'coloring', 'recognition'],
      }),
      makeDoc({
        id: 'interactive-art-sketch',
        title: 'Sketch & Observe',
        description: 'Simple drawing prompts with helpful hints. Draw and have fun!',
        grades: ['g2', '35', '68'],
        difficulty: 'Beginner',
        focus: ['drawing', 'creativity', 'imagination'],
      }),
      makeDoc({
        id: 'interactive-art-patterns',
        title: 'Pattern & Symmetry Art',
        description: 'Create patterns and explore symmetry through drawing and coloring activities.',
        grades: ['35', '68'],
        difficulty: 'Intermediate',
        focus: ['patterns', 'symmetry', 'artistic skills'],
      }),
      makeDoc({
        id: 'interactive-art-perspective',
        title: 'Art & Perspective Practice',
        description: 'Learn about perspective, shading, and artistic techniques through guided exercises.',
        grades: ['68'],
        difficulty: 'Advanced',
        focus: ['perspective', 'shading', 'artistic techniques'],
      }),
      makeDoc({
        id: 'interactive-art-color-by-number',
        title: 'Color-by-Number Art',
        description: 'Color pictures using number codes. Each sheet features unique designs and color patterns.',
        grades: ['preK', 'k1', 'g2', '35'],
        difficulty: 'Beginner',
        focus: ['coloring', 'number recognition', 'fine motor', 'following directions'],
      }),
      makeDoc({
        id: 'interactive-art-mandala',
        title: 'Mandala Art & Patterns',
        description: 'Create beautiful mandala designs with patterns and symmetry. Perfect for mindfulness and creativity.',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['patterns', 'symmetry', 'mindfulness', 'concentration'],
      }),
      makeDoc({
        id: 'interactive-art-doodle',
        title: 'Doodle Art Challenge',
        description: 'Free-form doodling prompts that spark creativity and imagination. No rules, just fun!',
        grades: ['k1', 'g2', '35', '68'],
        difficulty: 'Beginner',
        focus: ['creativity', 'imagination', 'self-expression', 'artistic freedom'],
      }),
      makeDoc({
        id: 'interactive-art-seasonal',
        title: 'Seasonal Coloring Pages',
        description: 'Themed coloring pages for different seasons and holidays. Each sheet features unique seasonal designs.',
        grades: ['preK', 'k1', 'g2', '35'],
        difficulty: 'Beginner',
        focus: ['coloring', 'seasonal awareness', 'fine motor', 'creativity'],
      }),
      makeDoc({
        id: 'interactive-art-comic',
        title: 'Comic Strip Creator',
        description: 'Create your own comic strips with panels, speech bubbles, and characters. Tell a visual story!',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['storytelling', 'visual narrative', 'creativity', 'sequential art'],
      }),
      makeDoc({
        id: 'interactive-art-critique',
        title: 'Art Critique & Analysis',
        description: 'Learn to observe, describe, and analyze artwork using art vocabulary and critical thinking.',
        grades: ['35', '68'],
        difficulty: 'Advanced',
        focus: ['art analysis', 'critical thinking', 'vocabulary', 'observation skills'],
      }),
    ],
  },
  {
    id: 'early-learning',
    label: 'Early Learning',
    icon: '🌈',
    tagline: 'Foundational skills for preschool and kindergarten.',
    longDescription:
      'Letter, number, shape, and fine motor practice printables that keep littles engaged while building core skills.',
    topics: ['Alphabet tracing', 'Counting & numbers', 'Shapes & colors', 'Fine motor'],
    docs: [
      makeDoc({
        id: 'interactive-early-phonics',
        title: 'Phonics Fun Practice',
        description: 'Letter sounds, beginning sounds, and CVC word practice. Each sheet focuses on different sounds.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['phonics', 'letter sounds', 'reading readiness'],
      }),
      makeDoc({
        id: 'interactive-early-counting',
        title: 'Counting & Number Recognition',
        description: 'Interactive counting exercises with one-to-one correspondence practice.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['counting', 'number recognition', 'math readiness'],
      }),
      makeDoc({
        id: 'interactive-early-patterns',
        title: 'Pattern Recognition Explorer',
        description: 'Complete and create patterns with colors, shapes, and numbers.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['patterns', 'logic', 'critical thinking'],
      }),
      makeDoc({
        id: 'interactive-early-shapes',
        title: 'Shape & Color Explorer',
        description: 'Identify and match shapes and colors with interactive sorting activities.',
        grades: ['preK', 'k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['shapes', 'colors', 'classification'],
      }),
      makeDoc({
        id: 'interactive-early-letters',
        title: 'Letter Formation Practice',
        description: 'Trace and write uppercase and lowercase letters with guided practice.',
        grades: ['preK', 'k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['letter formation', 'handwriting', 'fine motor'],
      }),
      makeDoc({
        id: 'interactive-early-numbers',
        title: 'Number Writing & Recognition',
        description: 'Practice writing numbers 1-20 and matching quantities to numerals.',
        grades: ['preK', 'k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['number writing', 'numeral recognition', 'quantity matching'],
      }),
      makeDoc({
        id: 'interactive-early-foundations',
        title: 'Foundational Skills Review',
        description: 'Review basic letter, number, and shape recognition skills. Perfect for remediation or review.',
        grades: ['g2', '35'],
        difficulty: 'Beginner',
        focus: ['foundational skills', 'review', 'remediation'],
      }),
      makeDoc({
        id: 'interactive-early-basics',
        title: 'Basic Skills Practice',
        description: 'Essential early learning skills including letter sounds, counting, and basic patterns.',
        grades: ['g2', '35', '68'],
        difficulty: 'Beginner',
        focus: ['basic skills', 'foundations', 'review'],
      }),
    ],
  },
  {
    id: 'logic',
    label: 'Critical Thinking',
    icon: '💡',
    tagline: 'Puzzles, riddles, and pattern challenges.',
    longDescription:
      'Printable brain teasers that sharpen reasoning, pattern spotting, and problem solving for a variety of ages.',
    topics: ['Logic grids', 'Pattern recognition', 'Sequencing', 'Puzzles & riddles'],
    docs: [
      makeDoc({
        id: 'interactive-logic-sequence',
        title: 'Sequencing Challenge',
        description: 'Order events, steps, and patterns logically. Each sheet has unique sequences.',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Intermediate',
        focus: ['sequencing', 'logic', 'order'],
      }),
      makeDoc({
        id: 'interactive-logic-prek',
        title: 'Simple Patterns & Sorting',
        description: 'Complete simple patterns and sort objects by color, size, or type.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['patterns', 'sorting', 'logic'],
      }),
      makeDoc({
        id: 'interactive-logic-matching',
        title: 'Matching & Memory Games',
        description: 'Match objects, pictures, and concepts. Practice memory and recognition skills.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['matching', 'memory', 'recognition'],
      }),
      makeDoc({
        id: 'interactive-logic-classification',
        title: 'Classification & Categorization',
        description: 'Sort and classify objects, pictures, and concepts into groups.',
        grades: ['k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['classification', 'categorization', 'critical thinking'],
      }),
      makeDoc({
        id: 'interactive-logic-analogies',
        title: 'Analogies & Relationships',
        description: 'Practice identifying relationships and completing analogies.',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['analogies', 'relationships', 'critical thinking'],
      }),
      makeDoc({
        id: 'interactive-logic-riddles',
        title: 'Brain Teaser Riddles',
        description: 'Solve riddles and brain teasers with varying difficulty levels.',
        grades: ['g2', '35', '68'],
        difficulty: 'Advanced',
        focus: ['critical thinking', 'problem solving', 'reasoning'],
      }),
      makeDoc({
        id: 'interactive-logic-deduction',
        title: 'Deductive Reasoning Quest',
        description: 'Use clues to solve mysteries and logic puzzles.',
        grades: ['35', '68'],
        difficulty: 'Advanced',
        focus: ['deductive reasoning', 'logic', 'critical thinking'],
      }),
    ],
  },
  {
    id: 'sel',
    label: 'Social Emotional',
    icon: '🧘',
    tagline: 'Mindfulness, empathy, and growth mindset printables.',
    longDescription:
      'Free SEL worksheets that encourage reflection, gratitude, empathy, and emotional regulation—ideal for morning meetings or counseling groups.',
    topics: ['Feelings & emotions', 'Mindfulness', 'Kindness challenges', 'Goal setting'],
    docs: [
      makeDoc({
        id: 'interactive-sel-mindfulness',
        title: 'Mindfulness & Reflection',
        description: 'Daily mindfulness exercises with breathing techniques and reflection prompts.',
        grades: ['k1', 'g2', '35'],
        difficulty: 'Beginner',
        focus: ['mindfulness', 'self-awareness', 'emotional regulation'],
      }),
      makeDoc({
        id: 'interactive-sel-prek',
        title: 'Feelings & Emotions Explorer',
        description: 'Identify and express feelings through pictures, simple words, and activities.',
        grades: ['preK', 'k1'],
        difficulty: 'Beginner',
        focus: ['emotions', 'feelings', 'self-expression'],
      }),
      makeDoc({
        id: 'interactive-sel-friendship',
        title: 'Friendship & Social Skills',
        description: 'Learn about making friends, sharing, taking turns, and being kind to others.',
        grades: ['preK', 'k1', 'g2'],
        difficulty: 'Beginner',
        focus: ['friendship', 'social skills', 'kindness'],
      }),
      makeDoc({
        id: 'interactive-sel-gratitude',
        title: 'Gratitude & Appreciation',
        description: 'Practice gratitude through writing, drawing, and reflection activities.',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['gratitude', 'appreciation', 'positive thinking'],
      }),
      makeDoc({
        id: 'interactive-sel-empathy',
        title: 'Empathy Builder',
        description: 'Practice perspective-taking and understanding others\' feelings through scenarios.',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['empathy', 'social skills', 'perspective-taking'],
      }),
      makeDoc({
        id: 'interactive-sel-goals',
        title: 'Goal Setting & Growth',
        description: 'Set and track personal and academic goals with action plans.',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['goal setting', 'growth mindset', 'self-reflection'],
      }),
      makeDoc({
        id: 'interactive-sel-conflict',
        title: 'Conflict Resolution Skills',
        description: 'Learn strategies to resolve conflicts peacefully and communicate effectively with others.',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['conflict resolution', 'communication', 'problem solving', 'social skills'],
      }),
      makeDoc({
        id: 'interactive-sel-regulation',
        title: 'Self-Regulation Strategies',
        description: 'Practice techniques to manage emotions, stay calm, and make thoughtful choices.',
        grades: ['k1', 'g2', '35', '68'],
        difficulty: 'Beginner',
        focus: ['self-regulation', 'emotional control', 'coping strategies', 'impulse control'],
      }),
      makeDoc({
        id: 'interactive-sel-kindness',
        title: 'Kindness Challenge',
        description: 'Complete daily acts of kindness and reflect on how kindness impacts yourself and others.',
        grades: ['preK', 'k1', 'g2', '35', '68'],
        difficulty: 'Beginner',
        focus: ['kindness', 'empathy', 'character building', 'positive actions'],
      }),
      makeDoc({
        id: 'interactive-sel-growth-mindset',
        title: 'Growth Mindset Practice',
        description: 'Develop a growth mindset by learning to embrace challenges, learn from mistakes, and persist.',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['growth mindset', 'resilience', 'perseverance', 'learning from failure'],
      }),
      makeDoc({
        id: 'interactive-sel-stress',
        title: 'Stress Management & Coping',
        description: 'Identify stress triggers and practice healthy coping strategies for managing anxiety and stress.',
        grades: ['35', '68'],
        difficulty: 'Advanced',
        focus: ['stress management', 'coping strategies', 'anxiety', 'wellness'],
      }),
      makeDoc({
        id: 'interactive-sel-character',
        title: 'Character Building & Values',
        description: 'Explore important character traits like honesty, respect, responsibility, and integrity.',
        grades: ['g2', '35', '68'],
        difficulty: 'Intermediate',
        focus: ['character traits', 'values', 'ethics', 'moral development'],
      }),
    ],
  },
]

export function getCategoryById(id: string): InteractiveCategory | undefined {
  return INTERACTIVE_CATEGORIES.find((c) => c.id === id)
}

export function getDocMeta(docId: string): InteractiveWorksheetDoc | undefined {
  for (const cat of INTERACTIVE_CATEGORIES) {
    const match = cat.docs.find((d) => d.id === docId)
    if (match) return match
  }
  return undefined
}
